Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
[INFO/SyncManager-1] child process calling self.run()
[INFO/SyncManager-1] manager serving at '\\\\.\\pipe\\pyc-12412-0-73x33txl'
[INFO/Process-4] child process calling self.run()
[INFO/Process-4] #2: Starting
[INFO/Process-3] child process calling self.run()
[INFO/Process-3] #1: Starting
[INFO/Process-2] child process calling self.run()
[INFO/Process-2] #0: Starting
[INFO/Process-2] #0: Model initialized
[INFO/Process-4] #2: Model initialized
[INFO/Process-3] #1: Model initialized
[INFO/MainProcess] sending shutdown message to manager
[INFO/Process-4] process shutting down
[INFO/SyncManager-1] process shutting down
[INFO/Process-3] #1: Error:  Error:  Input data={input_data}
[INFO/Process-2] #0: Error:  Error:  Input data={input_data}
[INFO/Process-3] process shutting down
[INFO/Process-2] process shutting down
[INFO/SyncManager-1] process exiting with exitcode 0
Process Process-4:
Traceback (most recent call last):
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mherzo\Documents\GitHub\tf-models\app\ui\evaluate_automl_multiproc_mapped.py", line 144, in evaluator
    if not input_data:
TypeError: 'NoneType' object cannot be interpreted as an integer
[INFO/Process-4] process exiting with exitcode 1
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mherzo\Documents\GitHub\tf-models\app\ui\evaluate_automl_multiproc_mapped.py", line 144, in evaluator
    if not input_data:
  File "<string>", line 2, in __len__
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\managers.py", line 818, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
[INFO/Process-2] process exiting with exitcode 1
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mherzo\Documents\GitHub\tf-models\app\ui\evaluate_automl_multiproc_mapped.py", line 144, in evaluator
    if not input_data:
  File "<string>", line 2, in __len__
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\managers.py", line 818, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\mherzo\AppData\Local\Continuum\anaconda3\envs\ML\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
[INFO/Process-3] process exiting with exitcode 1
Python version: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
# processes 3
In paint 1 1 272 257
Traceback (most recent call last):
  File "C:\Users\mherzo\Documents\GitHub\tf-models\app\ui\evaluate_automl_multiproc_mapped.py", line 460, in <module>
    main_par(args)
  File "C:\Users\mherzo\Documents\GitHub\tf-models\app\ui\evaluate_automl_multiproc_mapped.py", line 325, in main_par
    for img_dict in get_images():
  File "C:\Users\mherzo\Documents\GitHub\tf-models\app\ui\evaluate_automl_multiproc_mapped.py", line 49, in get_images
    logger.info(f'Initializing video stream')
NameError: name 'logger' is not defined
[INFO/MainProcess] process shutting down
[INFO/MainProcess] calling join() for process Process-2
[INFO/MainProcess] calling join() for process Process-4
[INFO/MainProcess] calling join() for process Process-3
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
